### PR TITLE
iris and cartopy releases

### PR DESCRIPTION
**Pull request by marqh**
updates for the iris 1.8 and cartopy 0.12 releases

http://marqh.github.io/scitools.org.uk/

### CODE REVIEW

**Comment by bjlittle** [comment]
:+1:

**Comment by pelson** [comment]
Just checking you are aware of https://github.com/SciTools/scitools.org.uk#adding-built-docs

**Comment by pelson** [comment]
Also, did you get any errors when building the cartopy docs? The UN flag example hasn't come out http://scitools.org.uk/cartopy/docs/latest/examples/un_flag.html. I'm happy to patch example this ad-hoc rather than needing to re-build everything, but I'm just curious what went wrong...

**Comment by marqh** [comment]
there is an error trace, I missed it in the rather noisy output of warnings:
{code:}
/net/home/h04/itmh/scitools/cartopy/docs/source/examples/un_flag.rst:6: WARNING: Exception occurred in plotting un_flag
 from /net/home/h04/itmh/scitools/cartopy/docs/source/examples/un_flag.py:
Traceback (most recent call last):
  File "/usr/local/sci/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/sphinxext/plot_directive.py", line 515, in run_code
    exec code in ns
  File "<string>", line 4, in <module>
  File "<string>", line 110, in main
AttributeError: type object 'Path' has no attribute 'circle'

{code}

**Comment by pelson** [comment]
Thanks @marqh. Suspect it is a v1.4 vs v1.3 issue for matplotlib. As I say, we can just wire in the existing image (from v0.12.0rc1) into v0.12.0 and it will be a-ok.

**Comment by marqh** [comment]
https://github.com/SciTools/cartopy/blob/master/requirements/plotting.txt
lists the requirement on matplotlib as
matplotlib>=1.3.0

so I expected 1.3.1 to work effectively

I'll leave it up to you whether you'd rather change this example to work with 1.3.0 of update the requirements to mandata matplotlib 1.4

**Comment by pelson** [comment]
> I'll leave it up to you whether you'd rather change this example to work with 1.3.0 of update the requirements to mandata matplotlib 1.4

Neither. The requirement for cartopy *is* >=1.3. That isn't the same as the requirements for a specific example in the gallery.
